scan:
  millis: 3000
directory:
  path:
    scanned: "directoryScan/inBox"
    target: "directoryScan/inProgress"
    duplicate: "directoryScan/duplicate"
    successful: "directoryScan/successful"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customs payments
    username: main-root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect